[package]
name = "werk_test"
version = "0.1.0"
authors = ["est31 <MTest31@outlook.com>", "The opus project developers"]
license = "BSD-3-Clause"

[dependencies]
werk = { path = "../werk" }

[build-dependencies]
cc = { version = "1.0", features = ["parallel"] }
